# Phần 1: Khám phá Tensor

## Task 1.1: Tạo Tensor

In [1]:
import torch
import numpy as np

# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")

# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")

# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")

# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.2528, 0.1236],
        [0.3835, 0.4135]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


## Task 1.2: Các phép toán trên Tensor

In [4]:
# Cộng x_data với chính nó
result_add = x_data + x_data
print(f"Cộng x_data với chính nó:\n {result_add}\n")

# Nhân x_data với 5
result_mul = x_data * 5
print(f"Nhân x_data với 5:\n {result_mul}\n")

# Nhân ma trận x_data với x_data.T (chuyển vị)
result_matmul = x_data @ x_data.T
print(f"Nhân ma trận x_data với x_data.T:\n {result_matmul}\n")

Cộng x_data với chính nó:
 tensor([[2, 4],
        [6, 8]])

Nhân x_data với 5:
 tensor([[ 5, 10],
        [15, 20]])

Nhân ma trận x_data với x_data.T:
 tensor([[ 5, 11],
        [11, 25]])



## Task 1.3: Indexing và Slicing

In [5]:
# Lấy ra hàng đầu tiên
first_row = x_data[0]
print(f"Hàng đầu tiên:\n {first_row}\n")

# Lấy ra cột thứ hai
second_column = x_data[:, 1]
print(f"Cột thứ hai:\n {second_column}\n")

# Lấy ra giá trị ở hàng thứ hai, cột thứ hai
value = x_data[1, 1]
print(f"Giá trị ở hàng thứ hai, cột thứ hai: {value}\n")

Hàng đầu tiên:
 tensor([1, 2])

Cột thứ hai:
 tensor([2, 4])

Giá trị ở hàng thứ hai, cột thứ hai: 4



## Task 1.4: Thay đổi hình dạng Tensor

In [6]:
# Tạo tensor có shape (4, 4)
tensor_4x4 = torch.rand(4, 4)
print(f"Tensor shape (4, 4):\n {tensor_4x4}\n")

# Biến đổi thành tensor shape (16, 1) bằng view
tensor_16x1_view = tensor_4x4.view(16, 1)
print(f"Tensor shape (16, 1) sử dụng view:\n {tensor_16x1_view}\n")

# Hoặc sử dụng reshape
tensor_16x1_reshape = tensor_4x4.reshape(16, 1)
print(f"Tensor shape (16, 1) sử dụng reshape:\n {tensor_16x1_reshape}\n")

Tensor shape (4, 4):
 tensor([[0.1445, 0.0500, 0.8082, 0.4110],
        [0.6949, 0.3326, 0.6555, 0.1460],
        [0.7252, 0.9389, 0.3868, 0.8290],
        [0.9189, 0.0014, 0.8447, 0.4978]])

Tensor shape (16, 1) sử dụng view:
 tensor([[0.1445],
        [0.0500],
        [0.8082],
        [0.4110],
        [0.6949],
        [0.3326],
        [0.6555],
        [0.1460],
        [0.7252],
        [0.9389],
        [0.3868],
        [0.8290],
        [0.9189],
        [0.0014],
        [0.8447],
        [0.4978]])

Tensor shape (16, 1) sử dụng reshape:
 tensor([[0.1445],
        [0.0500],
        [0.8082],
        [0.4110],
        [0.6949],
        [0.3326],
        [0.6555],
        [0.1460],
        [0.7252],
        [0.9389],
        [0.3868],
        [0.8290],
        [0.9189],
        [0.0014],
        [0.8447],
        [0.4978]])



# Phần 2: Tự động tính Đạo hàm vớ autograd

## Task 2.1: Thực hành với autograd

In [9]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")

# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")

# Thực hiện thêm các phép toán
z = y * y * 3

# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))

# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x0000016F53B7BC70>
Đạo hàm của z theo x: tensor([18.])


In [10]:
try:
    z.backward()
except RuntimeError as e:
    print(f"Lỗi khi gọi z.backward() lần thứ hai: {e}")


Lỗi khi gọi z.backward() lần thứ hai: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.


- Nếu gọi z.backward() một lần nữa thì bị lỗi. Vì:  Khi gọi z.backward() lần đầu, PyTorch tự động giải phóng computational graph để tiết kiệm bộ nhớ. Do đó, nếu gọi z.backward() lần nữa sẽ gây lỗi vì graph đã bị xóa.


# Phần 3: Xây dựng mô hình đầu tiên với torch.nn

## Task 3.1: Lớp nn.Linear

In [11]:
# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)

# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều

# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)

print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[-1.4780,  0.4462],
        [ 0.1764,  0.3427],
        [ 0.6021,  0.4622]], grad_fn=<AddmmBackward0>)


## Task 3.2: Lớp nn.Embedding

In [12]:
# Khởi tạo lớp Embedding cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])

# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)

print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 0.7303, -0.1620, -0.5812],
        [ 1.1414, -0.6844, -1.6756],
        [ 0.6844, -0.0927, -0.6888],
        [ 0.4024,  0.7646,  1.8503]], grad_fn=<EmbeddingBackward0>)


## Task 3.3: Kết hợp thành một nn.Module

In [13]:
from torch import nn
class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        # Định nghĩa các lớp (layer) bạn sẽ dùng
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU() # Hàm kích hoạt
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        # Định nghĩa luồng dữ liệu đi qua các lớp
        # 1. Lấy embedding
        embeds = self.embedding(indices)
        # 2. Truyền qua lớp linear và hàm kích hoạt
        hidden = self.activation(self.linear(embeds))
        # 3. Truyền qua lớp output
        output = self.output_layer(hidden)
        return output

# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]]) # một câu gồm 4 từ

output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")

Model output shape: torch.Size([1, 4, 2])
